development:
  adapter: redis
  url: redis://localhost:6379/1
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  port: <%= ENV['REDIS_PORT'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: fast-ridge-64559